#!/bin/sh
#
# bedtime          Start/Stop the bedtimed daemon.
#
# chkconfig: 2345 90 60
# description: bedtimed opens a socket to receive commands from the \
#              bedtime php scripts to run privileged operations \
#              on their behalf.

### BEGIN INIT INFO
# Provides: bedtimed
# Required-Start: $local_fs $syslog
# Required-Stop: $local_fs $syslog
# Default-Start:  2345
# Default-Stop: 90
# Short-Description: run bedtime daemon
# Description: bedtimed opens a socket to receive commands from the
#              bedtime php scripts to run privileged operations
#              on their behalf.
### END INIT INFO

PROG=/usr/share/bedtime/bin/bedtimed
NAME=bedtimed
PIDF=/var/run/bedtimed.pid

case "$1" in
start)
   printf "%-50s" "Starting $NAME..."
   $PROG
   printf "%s\n" "OK"
;;
status)
   printf "%-50s" "Checking $NAME..."
   if [ -f $PIDF ]; then
      PID=`cat $PIDF`
      if [ -z "`ps aux | grep ${PID} | grep -v grep`" ]; then
         printf "%s\n" "Process dead but pidfile exists"
      else
         echo "Running"
      fi
   else
      printf "%s\n" "Stopped"
   fi
;;
stop)
   printf "%-50s" "Stopping $NAME..."
   PID=`cat $PIDF`
   if [ -f $PIDF ]; then
      kill -HUP $PID
      printf "%s\n" "OK"
      rm -f $PIDF
   else
      printf "%s\n" "pidfile not found"
   fi
;;
restart)
   $0 stop
   $0 start
;;
*)
   echo $"Usage: $0 {start|status|stop|restart}"
   exit 1
esac
